// src/lib/constants.ts 
export const SITE = {
  name: "Otunba Odubanjo",
  description: "Full-Stack Software Developer building modern web applications, mobile apps, APIs, and business systems — from user interfaces and databases to deployment.",
  url: "https://otunba.name.ng",
  twitter: "@",
  defaultImage: "/og-image.png",
  phone: "+234 811 504 6415",
  keywords: [
    "full stack software developer",
    "full stack developer",
    "software developer",
    "web developer",
    "mobile app developer",
    "web application development",
    "mobile application development",
    "API development",
    "backend development",
    "React",
    "Next.js",
    "React Native",
    "Expo",
    "Node.js",
    "Express",
    "TypeScript",
    "MongoDB",
    "PostgreSQL",
  ],
  github: "https://github.com/otunba-codes",
  linkedin: "https://linkedin.com/in/otunba-odubanjo-2296b6239",
  email: "otunbaodubanjo@gmail.com",
  location: {
    city: "Lagos",
    region: "Lagos",
    country: "Nigeria",
  },
};